name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
#  - pandas=1.5.3 # https://beta.mamba.pm/channels/emscripten-forge/packages/pandas
  - numpy=1.25.2 # https://beta.mamba.pm/channels/emscripten-forge/packages/numpy
#  - scipy=1.11.1 # https://beta.mamba.pm/channels/emscripten-forge/packages/scipy
