name: xeus-python-kernel
channels:
#  - https://conda.anaconda.org/conda-forge/label/bw2io_dev
#  - https://conda.anaconda.org/conda-forge/label/bw2data_dev
#  - https://conda.anaconda.org/conda-forge/label/bw2calc_dev
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - pandas=1.5.3 # https://beta.mamba.pm/channels/emscripten-forge/packages/pandas
  - numpy=1.25.2 # https://beta.mamba.pm/channels/emscripten-forge/packages/numpy
  - scipy=1.11.1 # https://beta.mamba.pm/channels/emscripten-forge/packages/scipy
  # BRIGHTWAY DEPENDENCIES (NOT PURE PYTHON)
  - peewee=3.17.0 # https://beta.mamba.pm/channels/emscripten-forge/packages/peewee # required by Brightway, loaded from emscripten-forge
  - lxml=4.9.3 # https://beta.mamba.pm/channels/emscripten-forge/packages/lxml#info # required by Brightway, loaded from emscripten-forge
#  - bw2io=0.9.dev21 # https://anaconda.org/conda-forge/bw2io/files # loaded from conda-forge under the `dev` label
#  - bw2data=4.0.dev25 # https://anaconda.org/conda-forge/bw2data/files # loaded from conda-forge under the `dev` label
#  - bw2calc=2.0.dev14 # https://anaconda.org/conda-forge/bw2calc/files # loaded from emscripten-forge (cf. https://github.com/conda-forge/bw2calc-feedstock/pull/14)
